export const GET_CONTACTS_START = "GET_CONTACTS_START";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const DELETE_CONTACTS_START = "DELETE_CONTACTS_START";
export const DELETE_CONTACTS_SUCCESS = "DELETE_CONTACTS_SUCCESS";
export const DELETE_CONTACTS_FAIL = "DELETE_CONTACTS_FAIL";
